In [1]:
import numpy as np

In [2]:
python_list = [1,2,3,4,5]
python_list

[1, 2, 3, 4, 5]

In [3]:
np.array([11,12,13])

array([11, 12, 13])

In [4]:
numpy_array = np.array(python_list)
numpy_array

array([1, 2, 3, 4, 5])

In [5]:
len(numpy_array)

5

In [6]:
len(numpy_array.shape)

1

In [7]:
python_list_list = [[1,2] , [3,4]]
python_list_list

[[1, 2], [3, 4]]

In [8]:
numpy_array2 = np.array(python_list_list)

In [9]:
len(numpy_array2.shape)

2

In [10]:
len(numpy_array2)

2

In [11]:
numpy_array2.shape

(2, 2)

In [12]:
python_list_list = [[1,2,5] , [3,4,6]]
np.array(python_list_list).shape

(2, 3)

# Range

In [13]:
range(5)

range(0, 5)

In [14]:
len(range(5))

5

In [15]:
list(range(5))

[0, 1, 2, 3, 4]

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.random.randint(10)

5

In [21]:
# to make a random array

np.random.randint(5 , size = (2,2))

array([[0, 2],
       [1, 2]])

# Data types in numpy

In [22]:
a = [1,2,3,4,5]
arr = np.array(a)

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr.dtype

dtype('int64')

In [25]:
# changing the array datatype from 64 to 32

arr = np.array(a , dtype = np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [26]:
# float

arr2 = np.array(a, dtype = float)

In [27]:
a = [1.2,2.5,3,"4"]

In [28]:
type(a)

list

In [29]:
type(a[0])

float

In [30]:
np.array(a)

array(['1.2', '2.5', '3', '4'], dtype='<U32')

# NOTE: 
- one important thing is numpy automatically converts everything into a single datatype, which makes the execution easy

In [31]:
a = [1.2,2.5,3]

In [32]:
type(a[-1])

int

In [33]:
float_arr = np.array(a)

In [34]:
float_arr

array([1.2, 2.5, 3. ])

In [35]:
float_arr.astype(int)

array([1, 2, 3])

In [36]:
float_arr.astype(int).dtype

dtype('int64')

In [37]:
# or 
float_arr.astype(np.int64)

array([1, 2, 3])

# slicing numpy arrays
- to reduce length selection , similar to list in python

In [38]:
arr = np.random.rand(5,5)
arr

array([[0.13518364, 0.05039248, 0.72198088, 0.09126182, 0.30801914],
       [0.26187724, 0.39724787, 0.76416368, 0.40207707, 0.57380015],
       [0.38645549, 0.13398118, 0.86812397, 0.62569365, 0.04615075],
       [0.52504896, 0.39117937, 0.23585157, 0.08235326, 0.59565951],
       [0.20267239, 0.44215026, 0.30864439, 0.76835126, 0.4450925 ]])

In [39]:
arr.size 

25

In [40]:
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('float64')

In [42]:
# slicing 0 to 3 rows

arr[:4]

array([[0.13518364, 0.05039248, 0.72198088, 0.09126182, 0.30801914],
       [0.26187724, 0.39724787, 0.76416368, 0.40207707, 0.57380015],
       [0.38645549, 0.13398118, 0.86812397, 0.62569365, 0.04615075],
       [0.52504896, 0.39117937, 0.23585157, 0.08235326, 0.59565951]])

In [43]:
arr[:4].shape

(4, 5)

In [44]:
arr[:, :4 ]      # selects every rows and for column it will drop last one

array([[0.13518364, 0.05039248, 0.72198088, 0.09126182],
       [0.26187724, 0.39724787, 0.76416368, 0.40207707],
       [0.38645549, 0.13398118, 0.86812397, 0.62569365],
       [0.52504896, 0.39117937, 0.23585157, 0.08235326],
       [0.20267239, 0.44215026, 0.30864439, 0.76835126]])

In [45]:
arr[1,1]

0.3972478652047058

In [46]:
# to drop all the rows from backward when user dont know the size of the array
arr[:-2]

array([[0.13518364, 0.05039248, 0.72198088, 0.09126182, 0.30801914],
       [0.26187724, 0.39724787, 0.76416368, 0.40207707, 0.57380015],
       [0.38645549, 0.13398118, 0.86812397, 0.62569365, 0.04615075]])

# masking 

In [47]:
int_arr = np.random.randint(5 , size = (6,8))

In [48]:
int_arr

array([[2, 4, 1, 4, 2, 0, 1, 3],
       [1, 0, 3, 1, 4, 1, 0, 0],
       [4, 1, 3, 0, 0, 0, 3, 4],
       [4, 2, 3, 2, 0, 1, 4, 0],
       [2, 0, 0, 3, 1, 3, 2, 4],
       [1, 2, 1, 2, 4, 0, 4, 0]])

In [49]:
# selecting first row 

int_arr_0 = int_arr[0]
int_arr_0

array([2, 4, 1, 4, 2, 0, 1, 3])

In [50]:
# compares each element with user given value and return bool value

int_arr_0 == 0

array([False, False, False, False, False,  True, False, False])

In [52]:
(int_arr_0 == 0) | (int_arr_0 == 1)

array([False, False,  True, False, False,  True,  True, False])

In [54]:
# new bool array formation

int_arr_is012 = (int_arr_0 == 0) | (int_arr_0 == 1) | (int_arr_0 == 2)
int_arr_is012

array([ True, False,  True, False,  True,  True,  True, False])

In [55]:
# masking

int_arr_0[int_arr_is012]

array([2, 1, 2, 0, 1])

# Matix - transpose

In [56]:
marks = [[1,2,3,4] , [5,6,7,8] , [9,10,11,12]]

In [57]:
marks[0]

[1, 2, 3, 4]

In [58]:
marks[0][0] , marks[1][0] , marks[2][0]

(1, 5, 9)

In [60]:
marks_transpose = []
for j in range(len(marks)):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [61]:
marks_transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11]]

In [65]:
# transpose using numpy

marks_array = np.array(marks)

In [66]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [69]:
# normal matrix

marks_array.sum(axis = 1)

array([10, 26, 42])

In [71]:
# Transpose matrix

marks_array.T.sum(axis = 1)

array([15, 18, 21, 24])

# Numpy broadcasting

In [72]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
grace_marks = np.array([[1,2,3]])

In [77]:
marks_array + grace_marks

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [78]:
grace_marks.shape

(1, 3)

In [79]:
grace_marks = np.array([[1,2,3]]).T

In [80]:
marks_array + grace_marks

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [81]:
grace_marks.shape

(3, 1)

In [82]:
marks_array.shape

(3, 4)

# Matrix multiplication

In [108]:
marks = np.array(marks , dtype = float)

In [109]:
weight_list = [[0.4], [0.2], [0.2], [0.2]]

In [110]:
weight_list

[[0.4], [0.2], [0.2], [0.2]]

In [112]:
result = []
for i in range(len(marks)):
    for j in range(len(weight_list)):
        curr_sum = 0
        for k in range(len(marks[i])):
            curr_sum += marks[i][k] * weight_list[k][j]
        result.append(curr_sum)
        
        
        
# will check error later

IndexError: list index out of range

In [97]:
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
weight_array = np.array(weight_list)

In [99]:
weight_array

array([[0.4],
       [0.2],
       [0.2],
       [0.2]])

In [104]:
marks_array @ weight_array

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [102]:
marks_array.shape

(3, 4)

In [103]:
weight_array.shape

(4, 1)

# Tensor
- 3d arrays, 4d or 5d.... and so is known as tensor